### ISSUE TITLE
 angular2 support

### ISSUE THREAD

**Issue by githubashok** [dougiefresh49/gulp-material-docs#12]

**Comment by githubashok** [comment]
@dougiefresh49 can u please check it

**Comment by dougiefresh49** [comment]
hey @githubashok i do not have any plans for creating an angular 2 solution as most angular 2/4 projects are using webpack. There are some really good alternative already out there for angular 2/4

here are a few

[compodoc](https://compodoc.github.io/website/)
[GitBook](https://github.com/GitbookIO/documentation)


CompoDoc has a lot of really neat features like dependency trees etc

hope this helps

**Comment by githubashok** [comment]
Hi @dougiefresh49 , thank you for your reply, i have gone through compodoc it is really helpful
